# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7afefb5d59a6de3296b50891e736ba74c91325bdfb91ddb9f6338df6fc4566e5c8852947e3fc699a4b22b4c4d82fabcec33aa315d7b7c818a2d1dedd3d94496

test:
  secret_key_base: e1979d7e54f45740667ac20c99c6b2e46f6b492faff0b0b7ea6c3066cc5a7c06b9f63bc1b752f2c6d2cb4582e59e9e82c75c0a46b6608b0672f3dd59b3a9bff8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
